### ISSUE TITLE
forgetting solution 0 when dividing by x

### ISSUE THREAD

**Issue by PersonalPythonProgrammer** [BelTol3011/primitve-math#1]
3x^2+x has solution 0, but solver does not show it

**Comment by Belissimo-T** [comment]
@PersonalPythonProgrammer 
I think you are referring to the following lines in the README.md:
```
Reduce(D(3*x^2-x, x)=0, x)
(x = 0.16666666666666666)
```

0 is indeed a solution to the provided equation. However, in the README.md, first, a derivative with respect to x is taken. Hence, the solution to this equation is found: 6*x-1 = 0.

Regarding 3*x^2-x = 0: This is an equation that is yet too complex for the solver to solve. Thus, 0 (or any other concrete number) doesn't show up in the output of Reduce.

I couldn't find an example where a zero solution is missing and the solver finds all other solutions/the expression outputted by Reduce doesn't have the same solutions as its input.
